import { Headers } from "./_components/headers";
import { NextAuthProvider } from "./_providers/auth";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Carol",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative w-screen h-screen box-border flex flex-col">
          {/* <NextAuthProvider> */}
          {/* <Headers /> */}
          {children}
          {/* </NextAuthProvider> */}
        </div>
      </body>
    </html>
  );
}
